- name: Install NGINX packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - libnginx-mod-stream

- name: Create NGINX mandatory directories
  ansible.builtin.file:
    path: " {{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/nginx/sites-available/
    - /etc/nginx/sites-enabled/

- name: Copy the global NGINX configuration
  ansible.builtin.copy:
    src: nginx-conf/
    dest: /etc/nginx/
    mode: "0755"

- name: Copy the NGINX TLS/SSL parameters file
  ansible.builtin.template:
    src: ssl_params.j2
    dest: /etc/nginx/ssl_params
    mode: "0644"

- name: Install the default NGINX configuration file
  ansible.builtin.copy:
    dest: "/etc/nginx/sites-available/default"
    content: |
      server {
        listen 80;
        listen [::]:80;

        return 301 https://$host$request_uri;
      }
    mode: "0644"

- name: Create NGINX default symlink
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link
    force: true
    follow: false
    mode: "0644"

- name: Restart service NGINX
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
