- name: Install NGINX packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - libnginx-mod-stream

- name: Create NGINX mandatory directories
  ansible.builtin.file:
    path: " {{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/nginx/sites-available/
    - /etc/nginx/sites-enabled/

- name: Copy the global NGINX configuration
  ansible.builtin.copy:
    src: nginx-conf/
    dest: /etc/nginx/

- name: Copy the NGINX SSL parameters file
  ansible.builtin.template:
    src: ssl_params.j2
    dest: /etc/nginx/ssl_params

- name: Install services NGINX configuration files
  ansible.builtin.template:
    src: "sites-available/{{ item.filename }}.j2"
    dest: "/etc/nginx/sites-available/{{ item.name }}"
  with_items:
    - { filename: "etherpad", name: "etherpad.{{ fqdn }}", port: "9001" }
    - { filename: "search", name: "search.{{ fqdn }}", port: "8080" }
    - { filename: "proxitok", name: "cringe.{{ fqdn }}", port: "8081" }
    - { filename: "mail", name: "mail.{{ fqdn }}", port: "8181" }
    - { filename: "status", name: "status.{{ fqdn }}", port: "3001" }
    - { filename: "cloud", name: "cloud.{{ fqdn }}", port: "8000" }
    - { filename: "tt-rss", name: "news.{{ fqdn }}", port: "8280" }
    - { filename: "website", name: "{{ fqdn }}", port: "3000" }
    - { filename: "gitea", name: "git.{{ fqdn }}", port: "3002" }
    - { filename: "ssp", name: "password.{{ fqdn }}", port: "3003" }
    - { filename: "services", name: "services.{{ fqdn }}", port: "1313" }

- name: Install the default NGINX configuration file
  ansible.builtin.copy:
    dest: "/etc/nginx/sites-available/default"
    content: |
      server {
        listen 80;
        listen [::]:80;

        return 301 https://$host$request_uri;
      }

- name: Create symlinks
  file:
    src: "/etc/nginx/sites-available/{{ service_name }}"
    dest: "/etc/nginx/sites-enabled/{{ service_name }}"
    state: link
    force: yes
    follow: false
  loop:
    - etherpad.{{ fqdn }}
    - search.{{ fqdn }}
    - cringe.{{ fqdn }}
    - status.{{ fqdn }}
    - mail.{{ fqdn }}
    - cloud.{{ fqdn }}
    - news.{{ fqdn }}
    - git.{{ fqdn }}
    - password.{{ fqdn }}
    - "{{ fqdn }}"
    - "services.{{ fqdn }}"
    - default
  loop_control:
    loop_var: service_name

- name: Restart service NGINX
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
