---
- hosts: all
  roles:
  # - role: base

  # - role: security

  # - role: vitalk.secure-ssh
  #   become: yes
  #   ssh_user: "{{ ansible_ssh_user }}"
  #   ssh_identity_key: "{{ ssh_identity_key_path }}"

  # - role: nickjj.docker
  #   become: yes
  #   tags: ["docker"]
  #   docker__users: [
  #     "{{ ansible_ssh_user }}"
  #   ]
  #   docker__registries:
  #     - registry_url: "https://index.docker.io/v1/"
  #       username: "{{ docker_hub_username }}"
  #       password: "{{ docker_hub_password }}"
  #   ignore_errors: yes

  # - role: weareinteractive.ufw
  #   become: yes
  #   ufw_enabled: true
  #   ufw_packages: ["ufw"]
  #   ufw_rules:
  #     - logging: "full"
  #     - rule: allow
  #       to_port: '443'
  #     - rule: allow
  #       to_port: '80'
  #     - rule: allow
  #       name: Anywhere
  #       delete: true
  #   ufw_manage_config: true
  #   ufw_config:
  #     IPV6: "yes"
  #     DEFAULT_INPUT_POLICY: DROP
  #     DEFAULT_OUTPUT_POLICY: ACCEPT
  #     DEFAULT_FORWARD_POLICY: DROP
  #     DEFAULT_APPLICATION_POLICY: SKIP
  #     MANAGE_BUILTINS: "no"
  #     IPT_SYSCTL: /etc/ufw/sysctl.conf
  #     IPT_MODULES: ""

  # - role: shell

  # - role: profile

  # - role: geerlingguy.certbot
  #   become: yes
  #   vars:
  #     certbot_install_method: package
  #     certbot_auto_renew: true
  #     certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  #     certbot_auto_renew_hour: "3"
  #     certbot_auto_renew_minute: "30"
  #     certbot_create_if_missing: yes
  #     certbot_admin_email: nagi@tilde.team

  #   certbot_certs:
      # - domains:
      #   - joplin.{{ fqdn }}
      # - domains:
      #   - cringe.{{ fqdn }}
      # - domains:
      #   - status.{{ fqdn }}
      # - domains:
      #   - search.{{ fqdn }}
      # - domains:
      #   - etherpad.{{ fqdn }}
      # - domains:
      #   - "{{ fqdn }}"
      #   - www.{{ fqdn }}

  # - role: services

  - role: nginx

  # - role: tor
