version: '3.3'

services:
  etherpad:
    image: etherpad/etherpad:1.8.17
    container_name: etherpad
    ports:
      - '127.0.0.1:9001:9001'
    env_file:
      - .env
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
    
  db:
    image: postgres:11-alpine
    env_file:
      - .env
    logging:
      driver: "none"
    volumes:
      - etherpad_db:/var/lib/postgresql/data

volumes:
  etherpad_db: