- name: Include service role
  ansible.builtin.include_role:
    name: "service"
  vars:
    service_name: "services"
    service_fqdn: "services.{{ domain }}"
    service_nginx_port: "1313"
    service_certbot: true
    service_nginx: true
    service_tor: true
    service_docker_compose: true
    service_systemd_service: true
