version: '3'

services:
  ldap-service:
    image: osixia/openldap:1.5.0
    container_name: ldap-service
    env_file:
      - .env
    environment:
      LDAP_ORGANISATION: "Theo BORI Cafe"
    volumes:
      - slapd_db:/var/lib/ldap
      - slapd_config:/etc/ldap/slapd.d

    networks:
      - net

  phpldapadmin-service:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin-service
    ports:
      - 127.0.0.1:30001:443
    networks:
      - net
    environment:
      PHPLDAPADMIN_HTTPS: true
      PHPLDAPADMIN_LDAP_HOSTS: ldap-service

networks:
  net: # ldap_net with the top directory

volumes:
  slapd_db:
  slapd_config:
