- name: Install Tor package
  ansible.builtin.package:
    name: tor
    state: present

- name: Filling Tor configuration file (torrc)
  ansible.builtin.blockinfile: 
    state: present
    insertafter: EOF
    dest: /etc/tor/torrc
    content: |
      HiddenServiceDir /var/lib/tor/{{ fqdn }}/
      HiddenServicePort 80 {{ tor_unix_socket }}

- name: Restart service Tor
  ansible.builtin.service:
    name: tor
    state: restarted
    enabled: yes

- name: Store the Tor hostname
  ansible.builtin.shell: |
    cat /var/lib/tor/{{ fqdn }}/hostname
  register: tor_hostname

- name: Display the Tor hostname
  ansible.builtin.debug:
    msg: "{{ tor_hostname.stdout }}"
  when: tor_hostname is defined

- name: Configure NGINX for Tor hidden servives (subdomains)
  ansible.builtin.blockinfile: 
    state: present
    insertafter: EOF
    dest: "/etc/nginx/sites-available/{{ item.service_name }}"
    content: |
      server {
        listen {{ tor_unix_socket }};

        access_log /var/log/nginx/{{ item.service_name }}.log;

        {% if item.service_name == fqdn %}
          server_name {{ tor_hostname.stdout }};
        {% else %}
          server_name {{ item.service_name | split('.') | first }}.{{ tor_hostname.stdout }};
        {% endif %}

        location / {
          include proxy_params;
          proxy_pass http://localhost:{{ item.service_port }}/;
        }
      }
  with_items:
    - { service_name: "etherpad.{{ fqdn }}", service_port: "9001" }
    - { service_name: "search.{{ fqdn }}", service_port: "8080" }
    - { service_name: "cringe.{{ fqdn }}", service_port: "8081" }
    - { service_name: "mail.{{ fqdn }}", service_port: "8181" }
    - { service_name: "status.{{ fqdn }}", service_port: "3001" }
    - { service_name: "cloud.{{ fqdn }}", service_port: "8000" }
    - { service_name: "news.{{ fqdn }}", service_port: "8280" }
    - { service_name: "{{ fqdn }}", service_port: "3000" }
    - { service_name: "git.{{ fqdn }}", service_port: "3002" }
