- name: Install Tor package
  ansible.builtin.package:
    name: tor
    state: present

- name: Filling Tor configuration file (torrc)
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    dest: /etc/tor/torrc
    content: |
      HiddenServiceDir /var/lib/tor/{{ domain }}/
      HiddenServicePort 80 {{ tor_unix_socket }}

- name: Restart service Tor
  ansible.builtin.service:
    name: tor
    state: restarted
    enabled: true
