- name: Install Golang
  ansible.builtin.package:
    name: golang
    state: present

- name: Install dockerv
  ansible.builtin.shell: |
    go install github.com/theobori/dockerv@latest

- name: Init dockerv
  ansible.builtin.shell: |
    dockerv init

- name: Create full backup script
  ansible.builtin.template:
    src: backup-full.j2
    dest: /usr/local/scripts/backup-full
    mode: 0755

- name: Creates a cron file for the daily full services backup
  ansible.builtin.cron:
    name: daily backup
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: "PATH=\"${PATH}:/usr/local/bin\" /usr/local/scripts/backup-full"
