- name: Check if the scripts directory exists
  ansible.builtin.stat:
    path: /usr/local/scripts
  register: scripts_dir

- name: Git clone scripts
  ansible.builtin.git:
    repo: https://github.com/theobori-cafe/scripts
    dest: /usr/local/scripts/
  when: scripts_dir.stat.exists == false

- name: Install gobally the scripts
  ansible.builtin.shell: |
    make re -C /usr/local/scripts
