version: '3'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TTRSS_DB_USER}
      - POSTGRES_PASSWORD=${TTRSS_DB_PASS}
      - POSTGRES_DB=${TTRSS_DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - rss_net

  app:
    image: theobori/ttrss-fpm-pgsql-ldap-static:1.0
    build:
      dockerfile: .docker/app/Dockerfile
      context: https://github.com/theobori-cafe/tt-rss-ldap.git
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - db
    networks:
      - rss_net
      - ldap_net

  updater:
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - app
    command: /opt/tt-rss/updater.sh
    networks:
      - rss_net

  web-nginx:
    image: theobori/ttrss-web-nginx:1.0
    build:
      dockerfile: .docker/web-nginx/Dockerfile
      context: https://github.com/theobori-cafe/tt-rss-ldap.git
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app
    networks:
      - rss_net

networks:
  rss_net:
  ldap_net:
    external: true

volumes:
  db:
  app:
