- name: Ansible create the services directory if not exists
  ansible.builtin.file:
    path: /usr/local/services
    state: directory
    mode: 0755

- name: Copy the docker compose files
  ansible.builtin.copy:
    src: "{{ service_name }}"
    dest: "/usr/local/services/"
  loop:
    - proxitok
    - searxng
    - uptime-kuma
    - etherpad
    - ldap
    - nextcloud
    - tt-rss
    - theoboricafe
    - gitea
    - ssp
    - services
    - privatebin
    - calibre-web
  loop_control:
    loop_var: service_name

- name: Copy services environment files
  ansible.builtin.template:
      src: "{{ service_name }}/.env.j2"
      dest: "/usr/local/services/{{ service_name }}/.env"
      mode: 0640
  loop:
    - etherpad
    - ldap
    - nextcloud
    - tt-rss
    - gitea
    - ssp
  loop_control:
    loop_var: service_name

- name: Create the Gitea log directory if not exists
  ansible.builtin.file:
    path: /usr/local/services/gitea/log
    state: directory
    owner: 1000
    group: 1000
    mode: 0755

- name: Create the Nextcloud log directory if not exists
  ansible.builtin.file:
    path: /usr/local/services/nextcloud/data
    owner: 33
    group: 33
    state: directory
    mode: 0755

- name: Create the tt-rss config.d directory if not exists
  ansible.builtin.file:
    path: /usr/local/services/tt-rss/config.d
    state: directory
    mode: 0755

- name: Copy the LDAP configuration PHP file
  ansible.builtin.template:
    src: tt-rss/config.d/ldap.php.j2
    dest: /usr/local/services/tt-rss/config.d/ldap.php

- name: Create systemd services
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ service_name }}.service"
    content: |
      [Unit]
      Description={{ service_name }} service
      Requires=docker.service
      After=docker.service

      [Service]
      Restart=on-failure

      WorkingDirectory=/usr/local/services/{{ service_name }}

      ExecStart=docker compose up --build
      ExecStop=docker compose down --remove-orphans

      [Install]
      WantedBy=multi-user.target
  loop:
    - etherpad
    - uptime-kuma
    - searxng
    - nextcloud
    - ldap
    - proxitok
    - tt-rss
    - theoboricafe
    - gitea
    - ssp
    - services
    - privatebin
    - calibre-web
  loop_control:
    loop_var: service_name
  notify:
    - Reload systemctl
